TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../rtl/bit_timing_sync.sv

TOPLEVEL = bit_timing_sync
MODULE = tb_bit_timing_sync

SIM ?= icarus
WAVES = 1

export PYTHONPATH=/usr/local/python/3.12.1/lib/python3.12/site-packages

include $(shell cocotb-config --makefiles)/Makefile.sim