class driver;
    mailbox #(transaction) mbx;
    virtual frame_if.DRIVER vif;
    logger log;
    
    function new(virtual frame_if.DRIVER vif,mailbox #(transaction) mbx);// why not logger 
        this.mbx = mbx;
        this.vif = vif;
        this.log= new("logs/driver.log");
    endfunction

    // wait using the mailbox to get the data from the drvTrx which have generated by the gen block
    task drvdata();  
        transaction drvTrx;
        vif.valid = 0;
        vif.frame_in = '0;
        forever begin
            mbx.get (drvTrx);
            wait(vif.tx_ready);
            @(posedge vif.clk);

                log.separator("Driving Transaction");
                log.info($sformatf("ID   = %03h",drvTrx.id));
                log.info($sformatf("DLC  = %0d",drvTrx.dlc));
                log.info($sformatf("DATA = %016h",drvTrx.data));
                vif.frame_in.id  = drvTrx.id;
                vif.frame_in.rtr = drvTrx.rtr;
                vif.frame_in.ide = drvTrx.ide;
                vif.frame_in.dlc = drvTrx.dlc;
                vif.frame_in.data= drvTrx.data;

                vif.valid <= 1;

            @(posedge vif.clk);
                vif.valid <= 0;
        end
    endtask
endclass
